name: Release Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'chart/**'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Mayastor Helm chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: .
